// platforms/calendar/client/components/header/header.tsx
'use client'

import HeaderGithub from './header-github'
import { HeaderThemeToggle } from './header-theme-toggle'
import { useAuth } from '@/contexts/auth-context'
import { Button } from '@/components/ui/button'

export default function Header() {
  const { isAuthenticated, logout } = useAuth()
  return (
    <div className="flex items-center justify-between p-2 w-full border-b">
      <div>
        <h1 className="text-lg font-bold">
          React, Tailwind and Shadcn Full Calendar
        </h1>
        <h3 className="text-muted-foreground">
          By <span className="font-bold">@charlietlamb</span>
        </h3>
      </div>
      <div className="flex items-center gap-2">
        {isAuthenticated && (
          <Button variant="outline" size="sm" onClick={logout}>
            Sign out
          </Button>
        )}
        <HeaderGithub />
        <HeaderThemeToggle />
      </div>
    </div>
  )
}

// platforms/profile-editor/client/src/lib/components/layout/Header.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { currentUser, logout } from '$lib/stores/auth';
	import { Button } from '@metastate-foundation/ui/button';
	import { Separator } from '@metastate-foundation/ui/separator';
</script>

<header class="flex h-16 items-center justify-between bg-card px-6">
	<div class="flex items-center gap-4 lg:hidden">
		<span class="text-lg font-semibold text-foreground">Profile Editor</span>
	</div>
	<div class="hidden lg:block"></div>

	<div class="flex items-center gap-4">
		{#if $currentUser}
			<span class="text-sm text-muted-foreground">{$currentUser.name ?? $currentUser.ename}</span>
		{/if}
		<Button
			variant="ghost"
			size="sm"
			onclick={() => { logout(); goto('/auth'); }}
		>
			Sign out
		</Button>
	</div>
</header>
<Separator />
