// platforms/file-manager/src/lib/components/UserMenuDropdown.svelte
<script lang="ts">
	import { currentUser, logout } from '$lib/stores/auth';
	import { goto } from '$app/navigation';

	let isOpen = $state(false);

	function handleLogout() {
		logout();
		goto('/auth');
		isOpen = false;
	}

	function toggleDropdown() {
		isOpen = !isOpen;
	}

	function closeDropdown() {
		isOpen = false;
	}
</script>

<div class="relative">
	<button
		onclick={toggleDropdown}
		class="flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
		type="button"
	>
		<span class="text-sm font-medium text-gray-700">
			{$currentUser?.name || $currentUser?.ename || 'User'}
		</span>
		<svg
			class="w-4 h-4 text-gray-500 transition-transform {isOpen ? 'rotate-180' : ''}"
			fill="none"
			stroke="currentColor"
			viewBox="0 0 24 24"
		>
			<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
		</svg>
	</button>

	{#if isOpen}
		<!-- Backdrop -->
		<div
			class="fixed inset-0 z-10"
			onclick={closeDropdown}
			role="button"
			tabindex="-1"
		></div>

		<!-- Dropdown Menu -->
		<div class="absolute right-0 mt-2 w-56 bg-white border border-gray-200 rounded-lg shadow-lg z-20 overflow-hidden">
			<!-- User Info Section -->
			<div class="px-4 py-3 border-b border-gray-200 bg-gray-50">
				<div class="text-sm font-medium text-gray-900">
					{$currentUser?.name || $currentUser?.ename || 'User'}
				</div>
				{#if $currentUser?.ename && $currentUser?.name}
					<div class="text-xs text-gray-500 mt-1">@{$currentUser.ename.replace(/^@+/, '')}</div>
				{/if}
			</div>

			<!-- Menu Items -->
			<div class="py-1">
				<button
					onclick={handleLogout}
					class="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 transition-colors flex items-center gap-2"
					type="button"
				>
					<svg
						class="w-4 h-4"
						fill="none"
						stroke="currentColor"
						viewBox="0 0 24 24"
					>
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"
						/>
					</svg>
					Logout
				</button>
			</div>
		</div>
	{/if}
</div>

// platforms/eCurrency/client/src/components/user-menu-dropdown.tsx
import { useState } from "react";
import { ChevronDown, LogOut, User } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { useQuery } from "@tanstack/react-query";
import { apiClient } from "@/lib/apiClient";

interface UserMenuDropdownProps {
  accountContext: { type: "user" | "group"; id: string } | null;
  onAccountContextChange: (context: { type: "user" | "group"; id: string } | null) => void;
}

export default function UserMenuDropdown({ accountContext, onAccountContextChange }: UserMenuDropdownProps) {
  const { user, logout } = useAuth();
  const [isOpen, setIsOpen] = useState(false);

  const { data: groups } = useQuery({
    queryKey: ["userGroups"],
    queryFn: async () => {
      const response = await apiClient.get("/api/groups/my");
      return response.data;
    },
    enabled: !!user,
  });

  const adminGroups = groups?.filter((g: any) => g.isAdmin) || [];
  const hasAdminGroups = adminGroups.length > 0;

  const currentLabel = accountContext?.type === "user"
    ? "My Account"
    : adminGroups.find((g: any) => g.id === accountContext?.id)?.name || "My Account";

  if (!user) {
    return null;
  }

  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 px-4 py-2 border rounded-lg hover:bg-gray-50"
      >
        <span className="text-sm font-medium">{user?.name || user?.ename || "Account"}</span>
        <ChevronDown className={`h-4 w-4 transition-transform ${isOpen ? "rotate-180" : ""}`} />
      </button>

      {isOpen && (
        <>
          <div
            className="fixed inset-0 z-10"
            onClick={() => setIsOpen(false)}
          />
          <div className="absolute right-0 mt-2 w-56 bg-white border rounded-lg shadow-lg z-20 overflow-hidden">
            {/* User info */}
            <div className="px-4 py-3 border-b bg-gray-50">
              <div className="text-sm font-medium">{user?.name || user?.ename}</div>
              {user?.ename && (
                <div className="text-xs text-muted-foreground mt-1">{user.ename}</div>
              )}
            </div>

            {/* Account switcher section */}
            {hasAdminGroups && (
              <>
                <div className="px-4 py-2 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                  Switch Account
                </div>
                <button
                  onClick={() => {
                    onAccountContextChange({ type: "user", id: user.id });
                    setIsOpen(false);
                  }}
                  className={`w-full text-left px-4 py-2 hover:bg-accent transition-colors flex items-center gap-2 ${
                    accountContext?.type === "user" ? "bg-primary/10" : ""
                  }`}
                >
                  <User className="h-4 w-4" />
                  My Account
                </button>
                {adminGroups.map((group: any) => (
                  <button
                    key={group.id}
                    onClick={() => {
                      onAccountContextChange({ type: "group", id: group.id });
                      setIsOpen(false);
                    }}
                    className={`w-full text-left px-4 py-2 hover:bg-accent transition-colors flex items-center gap-2 ${
                      accountContext?.type === "group" && accountContext?.id === group.id ? "bg-primary/10" : ""
                    }`}
                  >
                    <User className="h-4 w-4" />
                    {group.name}
                  </button>
                ))}
                <div className="border-t my-1" />
              </>
            )}

            {/* Logout button */}
            <button
              onClick={() => {
                logout();
                setIsOpen(false);
              }}
              className="w-full text-left px-4 py-2 hover:bg-destructive/10 text-destructive transition-colors flex items-center gap-2"
            >
              <LogOut className="h-4 w-4" />
              Logout
            </button>
          </div>
        </>
      )}
    </div>
  );
}
