// platforms/emover/client/src/app/(auth)/login/page.tsx
"use client";
import { useState, useEffect } from "react";
import { QRCodeSVG } from "qrcode.react";
import { ArrowRightLeft } from "lucide-react";
import { useAuth } from "@/lib/auth-context";
import { setAuthToken, setAuthId } from "@/lib/authUtils";
import { apiClient } from "@/lib/apiClient";

export default function LoginPage() {
    const { login } = useAuth();
    const [qrData, setQrData] = useState<string | null>(null);
    const [sessionId, setSessionId] = useState<string | null>(null);
    const [errorMessage, setErrorMessage] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        const fetchQRCode = async () => {
            try {
                const response = await apiClient.get("/api/auth/offer");
                const uri = response.data.uri;
                // Extract session from URI
                const url = new URL(uri);
                const session = url.searchParams.get("session");
                setQrData(uri);
                setSessionId(session);
                setIsLoading(false);
            } catch (error) {
                console.error("Failed to fetch QR code:", error);
                setIsLoading(false);
            }
        };

        fetchQRCode();
    }, []);

    useEffect(() => {
        if (!sessionId) return;

        const baseUrl = process.env.NEXT_PUBLIC_EMOVER_BASE_URL || "http://localhost:4003";
        const eventSource = new EventSource(
            `${baseUrl}/api/auth/sessions/${sessionId}`
        );

        eventSource.onmessage = (event) => {
            try {
                const data = JSON.parse(event.data);
                
                if (data.error && data.type === "version_mismatch") {
                    setErrorMessage(
                        data.message ||
                            "Your eID Wallet app version is outdated. Please update to continue."
                    );
                    eventSource.close();
                    return;
                }

                if (data.token && data.user) {
                    setAuthToken(data.token);
                    setAuthId(data.user.id);
                    window.location.href = "/";
                }
            } catch (error) {
                console.error("Error parsing SSE data:", error);
            }
        };

        eventSource.onerror = () => {
            eventSource.close();
        };

        return () => eventSource.close();
    }, [sessionId]);

    if (isLoading) {
        return (
            <div className="flex items-center justify-center min-h-screen bg-gray-50">
                <div className="text-center">
                    <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mb-4" />
                    <p className="text-gray-600">Loading...</p>
                </div>
            </div>
        );
    }

    return (
        <div className="flex min-h-screen w-full flex-col items-center justify-center p-4">
            <div className="mb-5 flex flex-col items-center gap-2 text-center">
                <div className="mb-4">
                    <div className="w-20 h-20 bg-blue-600 rounded-2xl mx-auto flex items-center justify-center shadow-xl transform rotate-12">
                        <ArrowRightLeft className="w-10 h-10 text-white transform -rotate-12" />
                    </div>
                </div>
                <h1 className="text-3xl font-bold text-gray-900">Emover</h1>
                <p className="text-gray-600">
                    Scan QR code with your eID Wallet to login
                </p>
            </div>

            <div className="mb-5 flex w-full max-w-[400px] flex-col items-center gap-5 rounded-xl bg-gray-100 p-5">
                <h2 className="text-gray-900">
                    Scan the QR code using your{" "}
                    <b>
                        <u className="text-sm">eID App</u>
                    </b>{" "}
                    to login
                </h2>
                {errorMessage && (
                    <div className="mb-4 rounded-lg border border-red-400 bg-red-100 p-4 text-red-700 w-full">
                        <p className="font-semibold">Authentication Error</p>
                        <p className="text-sm">{errorMessage}</p>
                    </div>
                )}
                {qrData && (
                    <article className="overflow-hidden rounded-2xl bg-white p-4">
                        <QRCodeSVG value={qrData} size={250} />
                    </article>
                )}
                <p className="text-center">
                    <span className="mb-1 block font-bold text-gray-600">
                        The code is valid for 60 seconds
                    </span>
                    <span className="block font-light text-gray-600">
                        Please refresh the page if it expires
                    </span>
                </p>
                <p className="w-full rounded-md bg-white/60 p-4 text-center text-xs leading-4 text-black/40">
                    You are entering Emover — an evault migration platform built
                    on the Web 3.0 Data Space (W3DS) architecture. Migrate your
                    evault to a new provider with your eID Wallet.
                </p>
            </div>

            <div className="text-sm text-gray-600 text-center">
                Don't have the eID Wallet app?{" "}
                <a
                    href="https://play.google.com/store/apps/details?id=foundation.metastate.eid_wallet"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:underline"
                >
                    Download here
                </a>
            </div>
        </div>
    );
}

// infrastructure/control-panel/src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { onDestroy, onMount } from 'svelte';
	import QRCode from 'qrcode';

	let offerUri = $state('');
	let sessionId = $state('');
	let qrDataUrl = $state('');
	let isLoading = $state(true);
	let error = $state<string | null>(null);
	let isMobile = $state(false);

	let eventSource: EventSource | null = null;
	let refreshTimer: ReturnType<typeof setTimeout> | null = null;

	function cleanupSse() {
		if (eventSource) {
			eventSource.close();
			eventSource = null;
		}
	}

	function cleanupTimer() {
		if (refreshTimer) {
			clearTimeout(refreshTimer);
			refreshTimer = null;
		}
	}

	function detectMobile() {
		if (typeof window === 'undefined') return;
		isMobile = window.innerWidth < 768;
	}

	function setupSse(id: string) {
		cleanupSse();
		eventSource = new EventSource(`/api/auth/sessions/${encodeURIComponent(id)}`);

		eventSource.onmessage = (event) => {
			try {
				const payload = JSON.parse(event.data as string) as
					| { status: 'success'; ename: string }
					| { status: 'error'; message: string };

				if (payload.status === 'success') {
					void (async () => {
						try {
							const completeRes = await fetch('/api/auth/complete', {
								method: 'POST',
								headers: { 'Content-Type': 'application/json' },
								body: JSON.stringify({ sessionId: id })
							});
							if (!completeRes.ok) {
								const completeBody = await completeRes.json().catch(() => ({}));
								throw new Error(
									(completeBody as { error?: string }).error ||
										`Finalize login failed (${completeRes.status})`
								);
							}
							goto('/');
						} catch (completeError) {
							error =
								completeError instanceof Error
									? completeError.message
									: 'Failed to finalize login';
						}
					})();
					return;
				}

				if (payload.status === 'error') {
					error = payload.message || 'Authentication failed';
					cleanupSse();
				}
			} catch (parseError) {
				console.error('[auth] Failed parsing SSE message:', parseError);
			}
		};

		eventSource.onerror = () => {
			cleanupSse();
		};
	}

	async function fetchOfferAndWatch() {
		isLoading = true;
		error = null;
		cleanupSse();
		cleanupTimer();

		try {
			const response = await fetch('/api/auth/offer');
			if (!response.ok) {
				throw new Error(`Failed to fetch auth offer (${response.status})`);
			}

			const data = (await response.json()) as { uri: string; sessionId: string };
			offerUri = data.uri;
			sessionId = data.sessionId;
			qrDataUrl = await QRCode.toDataURL(offerUri, { width: 280, margin: 2 });

			setupSse(sessionId);
			refreshTimer = setTimeout(() => {
				void fetchOfferAndWatch();
			}, 60000);
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to initialize login';
		} finally {
			isLoading = false;
		}
	}

	onMount(() => {
		detectMobile();
		window.addEventListener('resize', detectMobile);
		void fetchOfferAndWatch();
	});

	onDestroy(() => {
		if (typeof window !== 'undefined') {
			window.removeEventListener('resize', detectMobile);
		}
		cleanupSse();
		cleanupTimer();
	});
</script>

<div class="mx-auto flex min-h-[70vh] w-full max-w-3xl items-center justify-center p-6">
	<div class="w-full rounded-xl border border-gray-200 bg-white p-8 shadow-sm">
		<h1 class="text-2xl font-semibold text-gray-900">Control Panel Login</h1>
		<p class="mt-2 text-sm text-gray-600">
			Authenticate with your eID Wallet. Only admin eNames in the server allowlist can access
			this panel.
		</p>

		{#if error}
			<div class="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">
				{error}
			</div>
		{/if}

		<div class="mt-6 flex flex-col items-center gap-4 rounded-lg bg-gray-50 p-6">
			{#if isLoading}
				<div class="h-8 w-8 animate-spin rounded-full border-b-2 border-blue-600"></div>
				<p class="text-sm text-gray-600">Preparing authentication offer...</p>
			{:else if qrDataUrl}
				{#if isMobile}
					<a
						href={offerUri}
						class="rounded-lg bg-blue-600 px-6 py-3 font-medium text-white hover:bg-blue-700"
					>
						Open eID Wallet
					</a>
					<p class="text-center text-sm text-gray-600">
						Tap to open the wallet app and complete authentication.
					</p>
				{:else}
					<img
						src={qrDataUrl}
						alt="W3DS auth QR code"
						class="h-64 w-64 rounded-lg bg-white p-2"
					/>
					<p class="text-center text-sm text-gray-600">
						Scan this QR code with your eID Wallet app.
					</p>
				{/if}
			{/if}
		</div>

		<div class="mt-6 flex items-center justify-between">
			<p class="text-xs text-gray-500">Offer refreshes automatically every 60 seconds.</p>
			<button
				onclick={() => void fetchOfferAndWatch()}
				class="rounded-lg border border-gray-200 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
			>
				Refresh Offer
			</button>
		</div>
	</div>
</div>
