// infrastructure/control-panel/src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { onDestroy, onMount } from 'svelte';
	import QRCode from 'qrcode';

	let offerUri = $state('');
	let sessionId = $state('');
	let qrDataUrl = $state('');
	let isLoading = $state(true);
	let error = $state<string | null>(null);
	let isMobile = $state(false);

	let eventSource: EventSource | null = null;
	let refreshTimer: ReturnType<typeof setTimeout> | null = null;

	function cleanupSse() {
		if (eventSource) {
			eventSource.close();
			eventSource = null;
		}
	}

	function cleanupTimer() {
		if (refreshTimer) {
			clearTimeout(refreshTimer);
			refreshTimer = null;
		}
	}

	function detectMobile() {
		if (typeof window === 'undefined') return;
		isMobile = window.innerWidth < 768;
	}

	function setupSse(id: string) {
		cleanupSse();
		eventSource = new EventSource(`/api/auth/sessions/${encodeURIComponent(id)}`);

		eventSource.onmessage = (event) => {
			try {
				const payload = JSON.parse(event.data as string) as
					| { status: 'success'; ename: string }
					| { status: 'error'; message: string };

				if (payload.status === 'success') {
					void (async () => {
						try {
							const completeRes = await fetch('/api/auth/complete', {
								method: 'POST',
								headers: { 'Content-Type': 'application/json' },
								body: JSON.stringify({ sessionId: id })
							});
							if (!completeRes.ok) {
								const completeBody = await completeRes.json().catch(() => ({}));
								throw new Error(
									(completeBody as { error?: string }).error ||
										`Finalize login failed (${completeRes.status})`
								);
							}
							goto('/');
						} catch (completeError) {
							error =
								completeError instanceof Error
									? completeError.message
									: 'Failed to finalize login';
						}
					})();
					return;
				}

				if (payload.status === 'error') {
					error = payload.message || 'Authentication failed';
					cleanupSse();
				}
			} catch (parseError) {
				console.error('[auth] Failed parsing SSE message:', parseError);
			}
		};

		eventSource.onerror = () => {
			cleanupSse();
		};
	}

	async function fetchOfferAndWatch() {
		isLoading = true;
		error = null;
		cleanupSse();
		cleanupTimer();

		try {
			const response = await fetch('/api/auth/offer');
			if (!response.ok) {
				throw new Error(`Failed to fetch auth offer (${response.status})`);
			}

			const data = (await response.json()) as { uri: string; sessionId: string };
			offerUri = data.uri;
			sessionId = data.sessionId;
			qrDataUrl = await QRCode.toDataURL(offerUri, { width: 280, margin: 2 });

			setupSse(sessionId);
			refreshTimer = setTimeout(() => {
				void fetchOfferAndWatch();
			}, 60000);
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to initialize login';
		} finally {
			isLoading = false;
		}
	}

	onMount(() => {
		detectMobile();
		window.addEventListener('resize', detectMobile);
		void fetchOfferAndWatch();
	});

	onDestroy(() => {
		if (typeof window !== 'undefined') {
			window.removeEventListener('resize', detectMobile);
		}
		cleanupSse();
		cleanupTimer();
	});
</script>

<div class="mx-auto flex min-h-[70vh] w-full max-w-3xl items-center justify-center p-6">
	<div class="w-full rounded-xl border border-gray-200 bg-white p-8 shadow-sm">
		<h1 class="text-2xl font-semibold text-gray-900">Control Panel Login</h1>
		<p class="mt-2 text-sm text-gray-600">
			Authenticate with your eID Wallet. Only admin eNames in the server allowlist can access
			this panel.
		</p>

		{#if error}
			<div class="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">
				{error}
			</div>
		{/if}

		<div class="mt-6 flex flex-col items-center gap-4 rounded-lg bg-gray-50 p-6">
			{#if isLoading}
				<div class="h-8 w-8 animate-spin rounded-full border-b-2 border-blue-600"></div>
				<p class="text-sm text-gray-600">Preparing authentication offer...</p>
			{:else if qrDataUrl}
				{#if isMobile}
					<a
						href={offerUri}
						class="rounded-lg bg-blue-600 px-6 py-3 font-medium text-white hover:bg-blue-700"
					>
						Open eID Wallet
					</a>
					<p class="text-center text-sm text-gray-600">
						Tap to open the wallet app and complete authentication.
					</p>
				{:else}
					<img
						src={qrDataUrl}
						alt="W3DS auth QR code"
						class="h-64 w-64 rounded-lg bg-white p-2"
					/>
					<p class="text-center text-sm text-gray-600">
						Scan this QR code with your eID Wallet app.
					</p>
				{/if}
			{/if}
		</div>

		<div class="mt-6 flex items-center justify-between">
			<p class="text-xs text-gray-500">Offer refreshes automatically every 60 seconds.</p>
			<button
				onclick={() => void fetchOfferAndWatch()}
				class="rounded-lg border border-gray-200 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
			>
				Refresh Offer
			</button>
		</div>
	</div>
</div>

// platforms/eVoting/src/app/(auth)/login/page.tsx
"use client";
import { useState, useEffect } from "react";
import { Card, CardHeader } from "@/components/ui/card";
import { QRCodeSVG } from "qrcode.react";
import { useAuth } from "@/lib/auth-context";
import { setAuthToken, setAuthId } from "@/lib/authUtils";
import { isMobileDevice, getDeepLinkUrl } from "@/lib/utils/mobile-detection";

export default function LoginPage() {
    const { login } = useAuth();
    const [qrData, setQrData] = useState<string | null>(null);
    const [sessionId, setSessionId] = useState<string | null>(null);
    const [error, setError] = useState<string | null>(null);
    const [errorMessage, setErrorMessage] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(true);
    const [isMobile, setIsMobile] = useState(false);

    useEffect(() => {
        setIsMobile(isMobileDevice());
    }, []);

    useEffect(() => {
        const fetchQRCode = async () => {
            try {
                const response = await fetch(
                    `${process.env.NEXT_PUBLIC_EVOTING_BASE_URL}/api/auth/offer`,
                    { method: "GET", headers: { "Content-Type": "application/json" } }
                );

                if (!response.ok) {
                    throw new Error("Failed to fetch QR code");
                }

                const data = await response.json();
                setQrData(data.offer);
                setSessionId(data.sessionId);
                setIsLoading(false);
            } catch {
                setError("Failed to load QR code");
                setIsLoading(false);
            }
        };

        fetchQRCode();
    }, []);

    useEffect(() => {
        if (!sessionId) return;

        const eventSource = new EventSource(
            `${process.env.NEXT_PUBLIC_EVOTING_BASE_URL}/api/auth/sessions/${sessionId}`
        );

        eventSource.onmessage = (event) => {
            try {
                const data = JSON.parse(event.data);
                
                // Check for error messages (version mismatch)
                if (data.error && data.type === 'version_mismatch') {
                    setErrorMessage(data.message || 'Your eID Wallet app version is outdated. Please update to continue.');
                    eventSource.close();
                    return;
                }

                // Handle successful authentication
                if (data.token && data.user) {
                    setAuthToken(data.token);
                    setAuthId(data.user.id);
                    window.location.href = "/";
                }
            } catch (error) {
                console.error("Error parsing SSE data:", error);
            }
        };

        eventSource.onerror = () => {
            eventSource.close();
        };

        return () => eventSource.close();
    }, [sessionId, login]);

    const getAppStoreLink = () => {
        if (typeof navigator === 'undefined') return "https://play.google.com/store/apps/details?id=foundation.metastate.eid_wallet";
        const userAgent = navigator.userAgent || navigator.vendor || (window as any).opera;
        if (/android/i.test(userAgent)) {
            return "https://play.google.com/store/apps/details?id=foundation.metastate.eid_wallet";
        }
        if (/iPad|iPhone|iPod/.test(userAgent) && !(window as any).MSStream) {
            return "https://apps.apple.com/in/app/eid-for-w3ds/id6747748667"
        }
        return "https://play.google.com/store/apps/details?id=foundation.metastate.eid_wallet";
    };

    return (
        <div className="flex flex-col items-center justify-center gap-4 min-h-screen px-4 pb-safe">
            {/* Logo + Tagline */}
            <div className="flex flex-col items-center text-center gap-4">
                <div className="flex items-center gap-2 text-2xl font-bold">
                    <img src="/Logo.png" alt="eVoting Logo" className="h-12" />
                    eVoting
                </div>
                <p className="text-lg sm:text-2xl">Secure voting in the W3DS</p>
            </div>

            {/* Main Card */}
            <Card className="flex flex-col items-center gap-4 w-full max-w-md p-4 pt-2 mx-4">
                <CardHeader className="text-foreground text-xl sm:text-2xl font-black text-center">
                    Welcome to eVoting
                </CardHeader>

                <div className="flex flex-col gap-4 text-muted-foreground items-center text-center">
                    {/* Dynamic heading text */}
                    <div className="text-lg sm:text-xl space-x-1">
                        {isMobile ? (
                            <>
                                <span>Click the button below using your</span>
                                <a href={getAppStoreLink()}><span className="font-bold underline">eID App</span></a>
                                <span>to login</span>
                            </>
                        ) : (
                            <>
                                <span>Scan the QR using your</span>
                                <a href={getAppStoreLink()}><span className="font-bold underline">eID App</span></a>
                                <span>to login</span>
                            </>
                        )}
                    </div>

                    {error && <div className="w-full text-red-500">{error}</div>}
                    
                    {errorMessage && (
                        <div className="w-full mb-4 p-4 bg-red-100 border border-red-400 text-red-700 rounded-lg">
                            <p className="font-semibold">Authentication Error</p>
                            <p className="text-sm">{errorMessage}</p>
                        </div>
                    )}

                    {isLoading ? (
                        <div className="w-48 h-48 bg-gray-100 rounded-lg flex items-center justify-center">
                            <div className="text-gray-500">Loading QR Code...</div>
                        </div>
                    ) : qrData ? (
                        <>
                            {isMobile ? (
                                <div className="flex flex-col gap-4 items-center">
                                    <a
                                        href={getDeepLinkUrl(qrData)}
                                        className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-center"
                                    >
                                        Login with eID Wallet
                                    </a>
                                    <div className="text-xs text-gray-500 max-w-xs">
                                        Click the button to open your eID wallet app
                                    </div>
                                </div>
                            ) : (
                                <div className="p-4 bg-white rounded-lg">
                                    <QRCodeSVG
                                        value={qrData}
                                        size={200}
                                        level="M"
                                        includeMargin={true}
                                    />
                                </div>
                            )}
                        </>
                    ) : (
                        <div className="w-48 h-48 bg-gray-100 rounded-lg flex items-center justify-center">
                            <div className="text-gray-500">QR Code not available</div>
                        </div>
                    )}

                    {/* Expiry Note */}
                    <div>
                        <p className="font-bold text-md">
                            The code is only valid for 60 seconds
                        </p>
                        <p>Please refresh the page if it expires</p>
                    </div>

                    {/* Info Box */}
                    <div className="bg-muted-foreground/20 p-4 rounded-md">
                        You are entering eVoting — a voting platform built on
                        the Web 3.0 Data Space (W3DS) architecture. This system
                        is designed around the principle of data-platform
                        separation, where all your personal content is stored in
                        your own sovereign eVault, not on centralised servers.
                    </div>
                </div>
            </Card>
            <a href="https://metastate.foundation" target="_blank" rel="noopener noreferrer">
                <img src="/W3DS.svg" alt="w3ds Logo" className="max-h-8" />
            </a>
        </div>
    );
}
