// platforms/pictique/src/lib/fragments/MaintenanceBanner/MaintenanceBanner.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import axios from 'axios';
	import { PUBLIC_REGISTRY_URL } from '$env/static/public';

	let motd = $state<{ status: 'up' | 'maintenance'; message: string } | null>(null);

	onMount(async () => {
		try {
			const registryUrl = PUBLIC_REGISTRY_URL || 'http://localhost:4321';
			const response = await axios.get(`${registryUrl}/motd`);
			motd = response.data;
		} catch (error) {
			console.error('Failed to fetch motd:', error);
		}
	});
</script>

{#if motd?.status === 'maintenance'}
	<div class="bg-yellow-500 px-4 py-3 text-center text-sm font-medium text-black">
		⚠️ {motd.message}
	</div>
{/if}

// platforms/eVoting/src/components/MaintenanceBanner.tsx
'use client';

import { useEffect, useState } from 'react';
import axios from 'axios';

interface Motd {
    status: 'up' | 'maintenance';
    message: string;
}

export function MaintenanceBanner() {
    const [motd, setMotd] = useState<Motd | null>(null);

    useEffect(() => {
        const fetchMotd = async () => {
            try {
                const registryUrl = process.env.NEXT_PUBLIC_REGISTRY_URL || 'http://localhost:4321';
                const response = await axios.get<Motd>(`${registryUrl}/motd`);
                setMotd(response.data);
            } catch (error) {
                console.error('Failed to fetch motd:', error);
            }
        };

        fetchMotd();
    }, []);

    if (motd?.status !== 'maintenance') {
        return null;
    }

    return (
        <div className="bg-yellow-500 px-4 py-3 text-center text-sm font-medium text-black">
            ⚠️ {motd.message}
        </div>
    );
}
